using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class NewClass1Test
{
    private Mock<IDisposable> _id;
    private NewClass1 _newClass1;
    [SetUp]
    public void SetUp()
    {
        _newClass1 = new NewClass1(_id.Object);
    }

    [Test]
    public void NewMethod3()
    {
        _newClass1.NewMethod3();
        Assert.Fail("autogenerated");
    }
}