using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class NewClass3Test
{
    private NewClass3 _newClass3;
    [SetUp]
    public void SetUp()
    {
        _newClass3 = new NewClass3();
    }

    [Test]
    public void NewMethod2()
    {
        var a = default(int);
        var b = default(string);
        _newClass3.NewMethod2(a, b);
        Assert.Fail("autogenerated");
    }
}