using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class NewClass2Test
{
    private NewClass2 _newClass2;
    [SetUp]
    public void SetUp()
    {
        _newClass2 = new NewClass2();
    }

    [Test]
    public void NewMethod1()
    {
        var a = default(int);
        var b = default(int);
        _newClass2.NewMethod1(a, b);
        Assert.Fail("autogenerated");
    }
}